spring:
  application:
    name: spring-cloud-feign
    
server:
  port: 1220
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:111111@KONTIN1:8761/eureka/,http://admin:111111@KONTIN2:8762/eureka/,http://admin:111111@KONTIN3:8763/eureka/
      
logging:
  level:
    com.wyh.springcloud.feign.client.*: debug