spring:
  application:
    name: spring-cloud-hystrix
    
server:
  port: 1221
  tomcat:
    max-threads: 3
  
feign:
  hystrix:
    enabled: true
    
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD#SEMAPHORE
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:111111@KONTIN1:8761/eureka/,http://admin:111111@KONTIN2:8762/eureka/,http://admin:111111@KONTIN3:8763/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream